// data-vyzev.js

const databazeVyzev = {
    "rim": {
        nazev: "Výzva do Říma!",
        celkoveKm: 1543,
        tridaPozadi: "pozadi-rim",      // Třída pro body
        tridaMapy: "",                  // Řím nemá speciální třídu na mapě
        mapaImg: "images/cesta-do-rima/mapa-rim.jpg",
        svgViewBox: "0 0 911 1197",
        // Zkopíruj sem tu dlouhou klikatou trasu d="..." z Říma
        svgPath: "M 550 45 L 507 95 L 454 260 L 420 300 L 418 380 L 330 399 L 253 452 L 263 486 L 260 558 L 220 703 L 250 832 L 245 928 L 255 995 L 325 1100 L 360 1170", 
        mapaSirka: 911,
        mapaVyska: 1197,
        povolitZoom: false,
        panacekHtml: "🏃‍♂️",            // V Římě běží jen emoji
        seznamMist: [
        { km: 1, nazev: "Praha", text: "Tvoje velká cesta začíná u orloje! Před tebou je 1543 km. Než vyrazíš, pořádně si zavaž boty, tohle bude jízda přes půl Evropy.", img: "images/cesta-do-rima/praha.jpg" },
        { km: 75, nazev: "Svatá Hora u Příbrami", text: "První velký milník v Čechách. Barokní areál Svaté Hory je jedno z nejslavnějších poutních míst ve střední Evropě. Ideální místo pro první odpočinek. Teď tě čeká běh až na Šumavu!", img: "images/cesta-do-rima/svata-hora.jpg" },
        { km: 200, nazev: "Boubínský prales", text: "Vstupuješ do jednoho z nejstarších pralesů v Evropě! Tato chráněná oblast byla založena už v roce 1858 a uvidíš tu stromy staré i přes 400 let. Po výstupu na rozhlednu tě čeká úchvatný výhled na Šumavu.", img: "images/cesta-do-rima/boubin.jpg" },
        { km: 285, nazev: "Pasov (Passau)", text: "Město tří řek! Tady se slévají Dunaj, Inn a Ilz. Oficiálně vstupuješ do Bavorska. Vychutnej si ten pohled na vodu, bude tě provázet dál.", img: "images/cesta-do-rima/passau.jpg" },
        { km: 345, nazev: "Braunau am Inn", text: "Procházíš historickým městečkem na břehu řeky Inn, které je známé svým středověkým centrem. Dominantou je pozdně gotický kostel svatého Štěpána s charakteristickou věží, který určitě nepřehlédneš.", img: "images/cesta-do-rima/braunau.jpg" },
        { km: 440, nazev: "Salzburg", text: "Zastávka v Mozartově rodišti. Nad městem se tyčí majestátní pevnost Hohensalzburg a vzduch je tu prosycen hudbou a historií.", img: "images/cesta-do-rima/salzburg.jpg" },
        { km: 535, nazev: "Kufstein", text: "Ikonická pevnost Kufstein stráží vstup do Tyrolska už po staletí. Tohle město na řece Inn tě okouzlí svou atmosférou a je to poslední zastávka před vysokými štíty Alp.", img: "images/cesta-do-rima/kufstein.jpg" },  
        { km: 645, nazev: "Innsbruck", text: "Hlavní město Alp a domov slavné Zlaté stříšky. Obklopují tě štíty vysoké přes 2000 metrů. Odtud tě čeká největší stoupání celé pouti.", img: "images/cesta-do-rima/innsbruck.jpg" },
        { km: 695, nazev: "Brenner", text: "Gratulace! Překonal jsi Brennerský průsmyk a oficiálně jsi v Itálii. Od teď už by se mělo jen oteplovat a těstoviny budou čím dál lepší.", img: "images/cesta-do-rima/brenner.jpg" },
        { km: 775, nazev: "Bolzano", text: "Vítej v Bolzanu! Nezapomeň pozdravit Ötziho – ledovcového muže, který tu odpočívá v muzeu už přes 5000 let. Ty jsi na tom s kondičkou naštěstí o dost lépe.", img: "images/cesta-do-rima/bolzano.jpg" },
        { km: 960, nazev: "Verona", text: "Město Romea a Julie. Můžeš si vystát řadu a zkusit zavolat pod balkonem, ale raději šetři dech na běh. Místní antická Aréna je naprosto dechberoucí!", img: "images/cesta-do-rima/verona.jpg" },
        { km: 1110, nazev: "Bologna", text: "Město věží a skvělého jídla. Tady vznikla nejstarší univerzita na světě a hlavně omáčka 'ragù alla bolognese'. Po tisíci kilometrech si pořádnou porci zasloužíš!", img: "images/cesta-do-rima/bologna.jpg" },
        { km: 1228, nazev: "Florencie", text: "Perla renesance. Stojíš v místě, kde tvořil Leonardo da Vinci i Michelangelo. Překroč řeku Arno přes most Ponte Vecchio a nasávej tu historii.", img: "images/cesta-do-rima/florencie.jpg" },
        { km: 1295, nazev: "Siena", text: "Vstoupil jsi do srdce Toskánska. Náměstí Piazza del Campo ve tvaru mušle je považováno za jedno z nejkrásnějších na světě. Už zbývá jen posledních 300 km!", img: "images/cesta-do-rima/siena.jpg" },
        { km: 1448, nazev: "Viterbo", text: "Starobylé 'Město papežů'. Už jsi skoro v cíli, cítíš ten vzduch z Říma? Viterbo bylo kdysi důležitější než samotný Řím, dnes je to oáza klidu před finále.", img: "images/cesta-do-rima/viterbo.jpg" },
        { km: 1543, nazev: "Řím", text: "DOKÁZAL JSI TO! Jako neohrožený gladiátor právě stojíš před Koloseem! 1543 km z Prahy až sem. Všechny cesty vedou do Říma a ta tvoje byla vítězná!", img: "images/cesta-do-rima/rim.jpg" }
        ]
    },
    
    "mount-doom": {
        nazev: "Mount Doom Challenge",
        celkoveKm: 2863,
        tridaPozadi: "pozadi-doom",     // Třída pro body
        tridaMapy: "mapa-doom",         // Třída pro kontejner mapy
        mapaImg: "images/middle-earth-empty.jpg",
        svgViewBox: "0 0 2087 1221",
        // Zkopíruj sem tu dlouhou trasu z Mordoru
        svgPath: "M 360 154 L 380 205 L 450 165 L 515 185 L 550 160 L 620 135 L 680 150 L 720 185 L 860 140 L 1009 135 L 960 304 L 1020 285 L 960 319 L 925 405 L 1028 409 L 1078 460 L 1155 495 L 1180 550 L 1280 615 L 1270 660 L 1325 665 L 1310 720 L 1345 739 L 1320 815 L 1320 900 L 1420 850 L 1540 910 L 1510 940 L 1509 1050 L 1520 1110 L 1628 1100 L 1590 1000 L 1640 980 L 1690 975 L 1690 1050",
        mapaSirka: 2087,
        mapaVyska: 1221,
        povolitZoom: true,
        panacekHtml: `<img src="images/mount-doom-challenge/ikona.png" alt="Hobiti Frodo a Sam" class="panacek-ikona-doom">`,
        seznamMist: [
            { km: 1, nazev: "Hobitín", text: "Vítej dobrodruhu! Právě ses pustil na dlouhou cestu po stopách dvou hobitů - Froda a Sama. Ti společně prošli skrze celou Středozemi až k samotné Hoře Osudu, kde se jim podařilo ukončit Třetí věk Středozemě vhozením Prstenu do Hory Osudu. Vše ale začíná tady v Hobitíně. Klidném místě, nacházejícím se v Kraji. Gandalf pověřil Froda se Samem důležitým úkolem. Musí se dostat do Hůrky, do hostince U Skákavého Poníka. I když se to ale ve filmu nezdá, Hůrka je od Hobitína vzdálená přibližně 250 kilometrů, máš tedy co dělat! Následující část cesty povede z Hobitína do Studánek. Nebude to trvat dlouho!", img: `images/mount-doom-challenge/hobitin.jpg` },
            { km: 49, nazev: "Studánky", text: "Právě jsi dorazil do Studánek! Frodův dům ve Studánkách sloužil jako krytí, pro Frodův odchod, kterým chtěl zmást Hobity po prodeji Dna Pytle v Hobitíně. V knižní verzi se zde Frodo a Sam setkávají s Pipinem a Smíškem, kteří již dávno o kouzelném Prstenu vědí a přidávají se k výpravě. Hobiti už věděli, že jsou pronásledováni Černými jezdci a proto zvolili cestu skrze Starý Hvozd. Po cestě tam tě ještě čeká zastávka u sedláka Červíka.", img: "images/mount-doom-challenge/studanky.jpg" },
            { km: 102, nazev: "Pole sedláka Červíka", text: "Máš za sebou už více než 100 kilometrů cesty s Frodem a Samem! Ti se zde ve filmové verzi setkávají se Smíškem a Pipinem a od této chvíle jsou součástí výpravy. Frodo měl už odmalička hrůzu z Červíkových velkých psů. V knižní verzi se spolu Frodo a sedlák Červík usmířili. Další část výpravy už bude mnohem nebezpečnější! Cesta vede do Starého Hvozdu.", img: "images/mount-doom-challenge/sedlak cervik.jpg" },
            { km: 125, nazev: "Starý Hvozd", text: "A je to tady! Přestože se hobiti zbavili Černých jezdců pochodem přes Starý Hvozd, čeká je neméně smrtonosné nebezpečí. Starý Hvozd je zalesněné území na východ od Kraje. Věřilo se, že stromy v tomto lese byly nepřátelské a bdělé. Listí šustilo i v bezvětší a v noci se ozýval šepot. Dokonce se zde záhadně přemisťovaly pěšiny. Hobiti z Rádovska pro ochranu své země před tímto lesem vysadili podél okraje Starého hvozdu Vysoké křoví - neprostupný živý plot. Když jednou začaly stromy růst příliš blízko Vysokého křoví, hobiti jich mnoho pokáceli a spálili na Vatrové pasece, kus cesty od západního okraje lesa. Od té doby se stromy stáhly od živého plotu, ale začaly být ještě nepřátelštějští.", img: "images/mount-doom-challenge/stary hvozd.jpg" },
            { km: 147, nazev: "Dědek Vrbák", text: "Starý Hvozd je nebezpečné místo a hobiti se o tom přesvědčili na vlastní kůži právě na tomto místě. Lesem protéká řeka Opletnice a u řeky roste strom, který není tak  úplně obyčejný. Je to zlý Huorn - dědek Vrbák. Ten hobity uspal a snažil se je pohltit. Zachránil je až tajuplný Tom Bombadil svou písničkou. Následně pak hobity pozval do svého nedalekého domu. Vydrž pár dalších kilometrů a dozvíš se o Tomovi něco více!", img: "images/mount-doom-challenge/dedek vrbak.jpg" },    
            { km: 167, nazev: "Dům Toma Bombadila", text: "Máš za sebou kus cesty a první smrtelné nebezpečí s hobity. Teď jsi ale v bezpečí, vítej u Toma! Tom Bombadil byla záhadná postava žijící ve Starém hvozdě. Mluví se o něm jako o nejstarší bytosti ve Středozemi a o jeho původu není nic známo. Má ženu Zlatěnku, se kterou se hobiti potkali v jejich domě pod kopcem, na východním okraji Starého Hvozdu. Byl úzce spojen s přírodou a ve své vlastní zemi, jejíž hranice si sám vymezil. Měl nesmírnou moc, takže bez problémů dokázal porazit zlé síly dědka Vrbáka. Dokonce byl jedinou bytostí, která si nasadila Jeden prsten a nejen, že na něj neměl žádný vliv, dokonce jej nechal dočasně zmizet. Pak jej vrátil zpět polekanému Frodovi. Tom Bombadil se nestaral o vnější svět a žádné války pro něj neměly význam. Byl prostě svůj.", img: "images/mount-doom-challenge/bombadil.jpg" },
            { km: 198, nazev: "Mohylové vrchy", text: "Právě si doběhl k pradávným Mohylovým vrchům a máš za sebou bezmála 200 kilometrů putování s hobity. Ve filmové verzi vynechaná scéna, avšak jedna z nejnebezpečnějších a nejdůležitějších částí celé výpravy. Osud čtveřice hobitů visel na vlásku. Zachránil je Tom Bombadil. Hobitům následně předal mocné zbraně z mohyly, které byly vykovány za dávných časů pro boj s vládcem Angmaru. Díky této shodě okolností bylo možné o dlouhou dobu později zranit vůdce Devítky a setnout z něj proroctví, kvůli kterému jej nemohl zabít žádný člověk. (Ve filmové verzi muž).", img: "images/mount-doom-challenge/mohylove vrchy.jpg" },
            { km: 255, nazev: "Hůrka", text: "Hůrka byla místem, kde se setkávalo mnoho cestovatelů, například trpaslíci, cestující po Velké cestě mezi svými sídly v Modrých horách a na východě. Hlavním společenským centrem městečka byl vyhlášený hostinec U Skákavého poníka, patřící rodině Máselníků. Je to první (a poslední?) hospoda na tvé trase! Urazil si 250 kilometrů cesty až sem, a hobiti se zde setkávají s tajemným Chodcem, který si je získal na svou stranu a putoval s nimi dále divočinou směrem k Roklince.", img: "images/mount-doom-challenge/hurka.jpg" },
            { km: 315, nazev: "Pustina", text: "Po stopách hobitů a Aragorna putuješ dál, až k bažinám v pustině. Aragorn se snažil hlavně setřást ze stopy Černé jezdce a udržet hobity naživu. Cesta z Hůrky až do Roklinky je dlouhá téměř 500 kilometrů nebezpečnou pustinou. Na dohled už je i Amon Sul - starodávné trosky strážné věže, kam teď vedou vaše kroky.", img: "images/mount-doom-challenge/pustina.jpg" },
            { km: 380, nazev: "Amon Sul", text: "Máš za sebou už 380 kilometrů cesty od Hobitína. Z Hůrky po stopách Aragorna a hobitů divočinou jsi urazil už 125 kilometrů až ses dostal sem na Amon Sûl. Název se překládá jako Větrný vrch. Když bylo založeno Severní království - Arnor, byla tu postavena mohutná strážní věž se stejným názvem Amon Sûl, která se stala stanovištěm jednoho z palantírů. Při válce s Černokněžným králem Angmaru byla strážní věž kompletně vypálena. 3. října 3018 tu byl čaroděj Gandalf obklíčen a přepaden hlídkujícími nazgûly a unikl jim. O tři dny později byla třemi nazgûly přepadena pod vrcholkem družina hobitů vedená Aragornem. Frodo tu byl raněn morgulskou dýkou. Tebe teď čeká přes 100 kilometrů dlouhá cesta divočinou až k Poslednímu mostu", img: "images/mount-doom-challenge/amon sul.jpg" },
            { km: 596, nazev: "Poslední most", text: "Máš za sebou další velký kus cesty až k Poslednímu mostu. Je to krátký kamenný most přes řeku Mitheithel. Dále se rozpíná divočina směrem až k Roklince. Zde podle knižní předlohy Glorfindel zahnal Prstenové přízraky a nechal Aragornovi a hobitům beryl na cestě jako znamená bezpečného průchodu. Ve filmové verzi se nic z těchto událostní nestane a družina zanedlouho potká Arwen.", img: "images/mount-doom-challenge/posledni most.jpg" },
            { km: 630, nazev: "Setkání s Arwen", text: "V divočině za mostem Aragorn zoufale hledal Athelas - Králův lístek pro zpomalení otravy Froda po zásahu Morgulského meče. Družinu zde dle filmového zpracování vystopuje Arwen a Froda zachrání tím, že jej naloží na svého koně Asfalotha a uhání s ním k Roklince. Nacházíš se přibližně 630 kilometrů od Hobitína a Frodova situace zde byla opravdu kritická. Uháněj dál k brodu přes řeku Bruinen! Hodně štěstí a ať tě přízraky nedohoní.", img: "images/mount-doom-challenge/arwen.jpg" },
            { km: 740, nazev: "Bruinen", text: "Uběhl jsi další velký kus cesty a do Roklinky už je to posledních pár kilometrů! Na tomto místě se nachází brod řeky Bruinen, kde se střetli Černí Jezdci s Arwen (ve filmovém zpracování) / Glorfindelem (v knižním zpracování). Výsledek byl pro jezdce stejný, řeka Bruinen jezdce smetla, zabila jejich koně a vzala jim hmotnou podobu. Řeka byla poslední linií obrany Roklinky. Teď už vzhůru tam, do posledního domáckého sídla elfů na Východě!", img: "images/mount-doom-challenge/bruinen.jpg" },
            { km: 752, nazev: "Roklinka", text: "Vítej v Roklince! Velká kapitola tvé výpravy je za tebou. Urazil jsi už více než 750 kilometrů! Cesta do Roklinky byla kriticky nebezpečná a hobiti ji zvládli, především za pomoci Aragorna. V Roklince se rozhodlo na velké Elrondově radě všech národů o osudu Jednoho Prstenu. Utvořilo se zde Společenstvo Prstenu a celá družina vedená Gandalfem se vydala na ještě delší a nebezpečnější cestu. Gandalf měl v plánu překonat Mlžné hory průsmykem Caradhras a to je další cíl i pro tebe! Cesta bude dlouhá, tak vydrž a pokračuj dále.", img: "images/mount-doom-challenge/roklinka.jpg" },
            { km: 890, nazev: "Cesta k průsmyku", text: "Urazil si se Společenstvem asi 140 kilometrů jížně od Roklinky podél Mlžných hor a na tomto místě družina narazila na špehujícími Crebainy, vyšlechtěné a vyslané Sarumanem. O plánu překonat hory průsmykem Caradhras už Saruman ví, přesto nezbývá, než se o náročný přechod pokusit. Cesta od tohoto táboru až k místu na vrcholcích hor, kde Společenstvo přizná porážku je dlouhá a nezbývá, než vydržet.", img: "images/mount-doom-challenge/crebain.jpg" },    
            { km: 1010, nazev: "Průsmyk Caradhras", text: "Nacházíš se už více než 1000 kilometrů od Hobitína. Je to obrovský úspěch a se Společenstvem ses dostal přes bažiny, divočinu, dlouhou prašnou cestu i starodávné lesy až na vrcholky Mlžných hor. Na tomto místě Společenstvo vzdalo pokus o Caradhras a vrací se poražené zpět. Hora zvítězila a nezbývá než hledat jinou cestu. Jako další v pořadí se nabízí cesta pod horami. Zatímco ve filmové verzi se do dolů v Morii nechce především Gandalfovi, v knižní verzi odmítá touto cestou jít Aragorn, který už v Morii v minulosti byl. Ten se podvolí až vůli celého Společenstva, varuje však Gandalfa před těmito kobkami. Čeká tě teď dlouhá cesta k branám Morie. Od tohoto místa je to ještě dalších 160 kilometrů.", img: "images/mount-doom-challenge/caradhras.jpg" },
            { km: 1100, nazev: "Přepadení Společenstva", text: "S Frodem a Samem jsi absolvoval už 1100 kilometrů na cestě z Hobitína. Dle knižní předlohy bylo přibližně na tomto místě Společenstvo přepadeno smečkou vlků, kteří je pronásledovali z hor. Díky Gandalfově ohni a zbraním ostatních se útok podařilo odrazit. Následovala pak rychlá cesta směrem k branám Morie, dříve než se vlci vrátí.", img: "images/mount-doom-challenge/prepadeni.jpg" },     
            { km: 1170, nazev: "Brány Morie", text: "Ve stopách Společenstva jsi doběhl až k branám Morie! Řekni přítel a vejdi. Nikdo netušil, co se v Morii stane. Gandalf a Aragorn byli jediní členové Společenstva, kteří už toto místo dříve navštívili. U bran Morie Společenstvo přepadl bezejmenný pozorovatel z vody a v Morii je uvěznil, už nebylo cesty zpět, pouze vpřed. Následující kilometry byly pro družinu extrémně náročné. Pohyb ve tmě, v tichosti a v tísnivé atmosféře po několik dlouhých dní.", img: "images/mount-doom-challenge/brana morie.jpg" },
            { km: 1230, nazev: "Balinova hrobka", text: "Prošel jsi ve stopách družiny už 50 kilometrů tmou a náročným terénem. Tady se družina zastavila u Balinovy hrobky. Balin byl příbuzný Gimliho a zabili jej zde skřeti. Také Společenstvo bylo přepadeno, tentokrát však proti skřetům stál čaroděj Gandalf a útok byl odražen - ne však na dlouho. Společenstvo se dalo do posledního zoufalého úprku Morií k můstku, který vedl k východu z Morie.", img: "images/mount-doom-challenge/gimli.jpg" },
            { km: 1249, nazev: "Souboj na můstku", text: "Právě procházíš po můstku, kde svedl souboj Gandalf a Balrog. Při souboji se oba zřítili do propasti a následně společně prchali tmou před nepojmenovanými stvořeními, které žijí v hlubinách světa. Při finálním souboji oba padli. Gandalf byl následně poslán zpět, aby dokončil svůj úkol ve Středozemi. K východu z Morie už to máš jen kousek, hned za rohem vidíš denní světlo!", img: "images/mount-doom-challenge/gandalf vs balrog.jpg" },
            { km: 1350, nazev: "Vstup do Lothlorienu", text: "Právě vstupuješ do Lothlorienu, nejkrásnějšího elfího království Třetího věku. Společenstvo do tohoto neobyčejného lesa vstoupilo po ztrátě Gandalfa ve velmi chmurném rozpoložení. Ty si můžeš užít nádherný les se stromy Mallorny, které rostou pouze zde. Mají zlaté listy a podle toho se lesu říká Zlatý les.", img: "images/mount-doom-challenge/lorien.jpg" },
            { km: 1440, nazev: "Caras Galadhon", text: "Dorazil si do Caras Galadhon, hlavního města a pevnosti elfské říše Lothlorien, které je postavené v korunách stromů, Mallornů. Město založila Galadriel a Celeborn jako obranu proti Dol Gulduru. Společenstvo zde našlo útočiště a zotavilo se ze svých cest, ty ale pokračuješ dál. Čeká tě nejdelší část cesty a to je plavba po řece Anduině.", img: "images/mount-doom-challenge/caras galadhon.jpg" },
            { km: 1455, nazev: "Plavba po Anduině", text: "Čeká tě nejdelší část tvého běhu! Start dlouhé cesty po vodním toku Anduiny. Pro Společenstvo to na elfích lodích nebyl takový problém. Ve filmovém zpracování trvala cesta pouze pár minut. Tebe ale čeká přes 400 kilometrů cesty, než doběhneš až k Argonathu a Raurorskému vodopádu.", img: "images/mount-doom-challenge/plavba.jpg" },    
            { km: 1890, nazev: "Sarn Gebir", text: "Konečně se blížíš ke konci této nekonečné plavby! Legolas v těchto místech poblíž Sarn Gebiru sestřelil Nazgula, který zaútočil na Společenstvo ze vzduchu. Z dálky už slyšíš bouření velkého Raurosu.", img: "images/mount-doom-challenge/legolas.jpg" },    
            { km: 1920, nazev: "Argonath", text: "Před tebou se právě tyčí dvě monumentální sochy Aragornových vzdálených předků Isildura a Anariona (ve filmovém zpracování - Elendila). Společenstvo tudy proplulo 25. února roku 3019. Pokochej se pohledem a nyní už musíme vyrazit dál. Blíží se důležitý moment, rozdělení celého Společenstva.", img: "images/mount-doom-challenge/argonath.jpg" },
            { km: 1980, nazev: "Rozpad Společenstva", text: "Konec tvé cesty podél řeky Anduiny je tady! Urazil jsi už téměr 2000 kilometrů spolu s hobity! A právě tady, 2000 kilometrů od startu tvé cesty se Společenstvo rozpadá. Poblíž Amon Hen byl Boromir zlákán mocí Prstenu a zaplatil za to životem. Pipin a Smíšek byli zajati. Aragorn, Gimli a Legolas se je vydali zachránit. Tebe ale čeká cesta nejtěžší - následovat Froda a Sama do bludiště skal Emyn Muil a pak najít cestu do samotného Mordoru.", img: "images/mount-doom-challenge/rozpad spolecenstva.jpg" },
            { km: 2080, nazev: "Vstup do Emyn Muil", text: "Právě stojíš na hranicích skalního bludiště Emyn Muil. Předtím, než vstoupíš do Mordoru se odtud musíš vymotat, tak jako Frodo a Sam. Těm se podařilo zajmout Gluma, který je ze skal dostal. Ty to musíš zvládnout sám. Mordor už je na dohled, tak to nevzdávej! ", img: "images/mount-doom-challenge/emyn muil.jpg" },
            { km: 2130, nazev: "Opuštění Emyn Muil", text: "Stejně jako Frodovi, Samovi a jejich průvodci Glumovi se i tobě podařilo dostat se z bludiště Emyn Muil. Teď před sebou vidíš dlouhé širé močály, kam oko dohlédne. A za nimi? Mordor! Vydrž, cíl je stále daleko, ale už na dohled!", img: "images/mount-doom-challenge/emyn muil2.jpg" },    
            { km: 2160, nazev: "Vstup do Mrtvých močálů", text: "Mrtvé močály jsou rozsáhlá bažinatá pustina, rozkládající se na planině Dagorlad. Zde byla v dávných dobách svedena velká bitva lidí a elfů proti Sauronovi. Ty se teď musíš těmito smradlavými močály proplést a dostat se na druhou stranu. Cesta bude dlouhá přibližně 60 kilometrů, tak si zacpi nos a utíkej!", img: "images/mount-doom-challenge/mrtve mocaly.jpg" },
            { km: 2220, nazev: "Opuštění Mrtvých močálů", text: "A jsi venku! Stejně jako hobitům, i tobě se podařilo dostat se z bludiště bažin. Teď už jsi na dohled k Černé Bráně do Mordoru!", img: "images/mount-doom-challenge/mrtve mocaly2.jpg" },    
            { km: 2230, nazev: "Černá Brána", text: "Černá Brána, neboli Morannon je hlavní vstup do Mordoru. Díváš se na tu monumentální bránu a láká tě vejít a zamířit přímo k Hoře Osudu, ale cesty hobitů, které následuješ vedou mnohem delší a složitější cestou. Nesmíš se nechat chytit a tak stejně jako hobiti, i ty musíš zamířit dál jinou cestou - tajnější a stejně nebezpečnou.", img: "images/mount-doom-challenge/cerna brana.jpg" },
            { km: 2380, nazev: "Setkání s Faramirem", text: "Od rozpadu Společenstva jsi uběhl už 400 kilometrů přes hory a bažiny. Teď je cesta alespoň na chvíli díky přírodě jednodušší. Vešel si totiž do severního Ithilienu. Zde hobiti poprvé zahlédli Olifanty a také došlo k nedobrovolnému setkání s Faramirem.", img: "images/mount-doom-challenge/faramir.jpg" },
            { km: 2450, nazev: "Opuštění Faramira", text: "Na tomto místě, poblíž Osgiliathu se Faramir rozhodl hobity s jejich posláním propustit a tak i ty můžeš jít v jejich stopách, tentokrát už opravdu rovnou do Mordoru. Čeká tě poslední a nejtěžší část cesty.", img: "images/mount-doom-challenge/faramir2.jpg" },
            { km: 2500, nazev: "Cirith Ungol", text: "Právě se nacházíš na začátku soutěsky Cirith Ungol. Musíš po stopách hobitů vyšplhat dlouhé strmé schody a následně se vydat do hrůzostrašné jeskyně Oduly, která má pořád hlad. Samovi se podařilo Odulu odrazit hlavně díky světlu Earendil, které hobiti získali od Galadriel na pomoc.", img: "images/mount-doom-challenge/cirith ungol2.jpg" },
            { km: 2540, nazev: "Únik ze soutěsky", text: "Podařilo se ti vymanit ze soutěsky Cirith Ungol, pravděpodobně té nejnebezpečnější jeskyně celé Středozemě! Otřep si pavučiny, Hora Osudu a tvůj finální cíl je už přímo před tebou! Bohužel, stejně jako hobitům, i tobě teď brání v průchodu k sopce armáda skřetů. Nasaď si skřetí zbroj a čeká tě poslední část zoufalé cesty - dlooouhý pochod plání Gorgoroth.", img: "images/mount-doom-challenge/cirith ungol3.jpg" },
            { km: 2740, nazev: "Pláň Gorgoroth", text: "Ušel si už 200 nekonečných kilometrů plání Gorgoroth. Vzduch je jen štiplavý dým, všude okolo skřeti, ostré skály a nebezpečí. Hora Osudu leží před tebou, posledních 120 kilometrů. Teď už to nemůžeš vzdát! Je neuvěřitelné, jakou vzdálenost museli ještě Frodo se Samem ujít Mordorem, než se konečně dostali do cíle.", img: "images/mount-doom-challenge/gorgoroth.jpg" },            
            { km: 2863, nazev: "Mount Doom", text: "Dokázal jsi to! Přešel jsi z Hobitína až do Mordoru. 2863 kilometrů nebezpečí a strastí máš za sebou! Zasloužíš si největší uznání, pokořil jsi tuto výzvu.", img: "images/mount-doom-challenge/mount doom.jpg" }            
        ]
    },

    "bradavice": {
        nazev: "Cesta do Bradavic",
        celkoveKm: 1010,
        tridaPozadi: "pozadi-bradavice",  
        tridaMapy: "mapa-bradavice",      
        mapaImg: "images/cesta-do-bradavic/mapa-bradavice.jpg", 
        svgViewBox: "0 0 1191 1232",      
        svgPath: "M 890 1001 L 906 949 L 890 909 L 870 897 L 882 859 L 858 797 L 822 769 L 819 722 L 850 673 L 842 649 L 798 637 L 784 615 L 767 581 L 754 537 L 744 516 L 710 489 L 678 477 L 629 470 L 582 466 L 553 445 L 548 429 L 565 413 L 553 401 L 527 402 L 503 407 L 476 410 L 465 394 L 474 368 L 470 353 L 457 353 L 422 357 L 427 370",   
        mapaSirka: 1191,                  
        mapaVyska: 1232,
        povolitZoom: true,                // Povolení zoomu pro trasu
        panacekHtml: `<img src="images/cesta-do-bradavic/ikona-vlak.png" alt="Bradavický expres" class="panacek-ikona-bradavice">`,              // Tematický panáček 
        seznamMist: [
            { km: 1, nazev: "Nástupiště 9 a 3/4", text: "Prošel jsi přepážkou na King's Cross a tvoje epická cesta začíná! Bradavický expres už sice odjel, ale ty to po svých zvládneš taky. Směr sever!", img: "images/cesta-do-bradavic/nastupiste.jpg" },
            { km: 100, nazev: "Cambridge", text: "Máš za sebou první stovku a probíháš kolem slavné univerzity. Mudlové tu sice studují bez hůlek, ale architektura už trochu připomíná bradavické chodby.", img: "images/cesta-do-bradavic/cambridge.jpg" },
            { km: 160, nazev: "Peterborough", text: "Vítej v Peterborough! Zastav se na chvíli u místní majestátní katedrály, naber dech a pokračuj dál na sever.", img: "images/cesta-do-bradavic/peterborough.jpg" },
            { km: 245, nazev: "Lincoln", text: "Lincolneshire je za tebou! Katedrála v Lincolnu posloužila při natáčení Harryho Pottera a Da Vinciho kódu. Nasaj trochu té filmové atmosféry.", img: "images/cesta-do-bradavic/lincoln.jpg" },
            { km: 325, nazev: "York", text: "Jsi v Yorku! Právě probíháš uličkou Shambles, která byla hlavní inspirací pro Příčnou ulici. Dávej pozor na výlohy a nekupuj zbytečně moc Bertíkových fazolek!", img: "images/cesta-do-bradavic/york.jpg" },
            { km: 385, nazev: "Goathland (Prasinky)", text: "Nádherná práce! Právě jsi dorazil na nádraží Goathland, které ve filmech představovalo vlakovou zastávku v Prasinkách. Už jsi skoro v polovině cesty!", img: "images/cesta-do-bradavic/goathland.jpg" },
            { km: 475, nazev: "Durham", text: "Polovina je za tebou! Durhamská katedrála posloužila pro natáčení bradavických nádvoří a učeben (např. učebna profesorky McGonagallové).", img: "images/cesta-do-bradavic/durham.jpg" },
            { km: 496, nazev: "Newcastle", text: "Probíháš přes Newcastle. Řeka Tyne tě povede dál na sever. Blížíš se k hranicím Skotska, přituhuje!", img: "images/cesta-do-bradavic/newcastle.jpg" },
            { km: 545, nazev: "Hrad Alnwick", text: "Poznáváš to tu? Hrad Alnwick sloužil pro natáčení exteriérů Bradavic v prvních dvou filmech. Tady se Harry učil létat na koštěti. Ty ale zůstaň nohama pevně na zemi a běž dál!", img: "images/cesta-do-bradavic/alnwick.jpg" },
            { km: 595, nazev: "Berwick-upon-Tweed", text: "Nejsevernější město Anglie! Cítíš ten chladnější vzduch? Právě překračuješ hranice a oficiálně vstupuješ do Skotska.", img: "images/cesta-do-bradavic/berwick.jpg" },
            { km: 684, nazev: "Edinburgh", text: "Vítej v hlavním městě Skotska a místě, kde J.K. Rowlingová napsala většinu knih o Harrym Potterovi! Tohle město dýchá magií na každém rohu.", img: "images/cesta-do-bradavic/edinburgh.jpg" },
            { km: 780, nazev: "Stirling", text: "Míjíš historický Stirling. Odsud už tě čeká ta pravá, divoká skotská vysočina (Highlands). Připrav se na kopečky!", img: "images/cesta-do-bradavic/stirling.jpg" },
            { km: 870, nazev: "Crianlarich", text: "Křižovatka skotské vysočiny. Jsi obklopený horami a jezery. Magie v ovzduší houstne, cíl se blíží!", img: "images/cesta-do-bradavic/crianlarich.jpg" },
            { km: 910, nazev: "Glencoe", text: "Zataj dech. Běžíš epickým údolím Glencoe. Tady stála Hagridova bouda a točily se tu úchvatné záběry z Vězně z Azkabanu. Posledních pár kilometrů!", img: "images/cesta-do-bradavic/glencoe.jpg" },
            { km: 950, nazev: "Glenfinnan Viaduct", text: "Slyšíš to houkání? Právě běžíš pod slavným viaduktem, přes který jezdí Bradavický expres! Most má 21 oblouků a za ním už tě čeká jen cíl.", img: "images/cesta-do-bradavic/glenfinnan.jpg" },
            { km: 1010, nazev: "Loch Shiel (Bradavice)", text: "DOKÁZAL JSI TO! Stojíš na břehu jezera Loch Shiel, které představovalo Černé jezero. V dálce už vidíš tyčit se bradavický hrad. 1010 kilometrů plných magie je za tebou!", img: "images/cesta-do-bradavic/loch-shiel.jpg" }
        ]
    }
}

